name: CI
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Lint
        run: npm run lint

      - name: Build (Vite -> dist/)
        run: npm run build

      - name: Upload build artifact (dist/)
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist/
